{
	"patcher" : 	{
		"fileversion" : 1,
		"appversion" : 		{
			"major" : 6,
			"minor" : 1,
			"revision" : 9,
			"architecture" : "x86"
		}
,
		"rect" : [ 554.0, 44.0, 519.0, 810.0 ],
		"bglocked" : 0,
		"openinpresentation" : 0,
		"default_fontsize" : 12.0,
		"default_fontface" : 0,
		"default_fontname" : "Helvetica Neue",
		"gridonopen" : 0,
		"gridsize" : [ 15.0, 15.0 ],
		"gridsnaponopen" : 0,
		"statusbarvisible" : 2,
		"toolbarvisible" : 1,
		"boxanimatetime" : 200,
		"imprint" : 0,
		"enablehscroll" : 1,
		"enablevscroll" : 1,
		"devicewidth" : 0.0,
		"description" : "",
		"digest" : "",
		"tags" : "",
		"boxes" : [ 			{
				"box" : 				{
					"fontface" : 1,
					"fontname" : "Helvetica Neue",
					"fontsize" : 12.0,
					"frgb" : 0.0,
					"id" : "obj-1",
					"linecount" : 41,
					"maxclass" : "comment",
					"numinlets" : 1,
					"numoutlets" : 0,
					"patching_rect" : [ 30.0, 180.0, 448.0, 593.0 ],
					"presentation_rect" : [ 34.0, 180.0, 0.0, 0.0 ],
					"text" : "1. Augment record-playback mechanism to record & playback odot bundles from m158.o.io.mouse (you may also use the Esplora). For this assignment, we'd like you to:\n\n    (a) implement a gate to start/stop recording of data;\n    (b) use an instrument that will receive & interpret your control data;\n    (c) take steps to filter out jitter & noise (if using the Esplora);\n    (d) make sure the playback mechanism generates some sound.\n\nThe instrument itself may be relatively simple, but avoid working with trivial, uninspired sounds (controlling interesting parameters yields interesting & expressive gestures - we recommend you use past labs to avoid getting overwhelmed with (b) and focusing on dealing with control data).\n\n2. Using the drum machine example showed in Wednesday's lecture, implement an approach for \"humanistic\" playback by adding random deviations from the generated time grid. You might want to start with the regular time grid generated by aseq function in o.expr.codebox. Your mission is to alter these values.\n\nAlthough the mechanism for this can be quite simple, you are invited to entertain different approaches to this problem. The simplest way is to compute some number (a time-offset) and add that number to an existing time-step. One possible improvement would be to keep track of the event-number (/index in o.listenumerate) and introduce deviations from the aseq-function times that are dependent on the event number.  (Note that you may also avoid using aseq and figure out other ways of generating interesting rhythms - the \"humanizer\" that jitters the time values around should work for any list of time-deltas-from-timetag we looked at in lecture.)\n\n3. You may opt out of both of the above by working on your Final Project instead. The protocol for this choice consists of:\n\n   (a) sending an email to your GSI that briefly (two-three sentences) outlines what you will be doing and why (what is the goal of this week's work on the Final Project);\n   (b) we will try our best to address any concerns as soon as possible (this may not work out for us if everyone sends us emails...);\n   (c) will use your email (proposal) as the grading rubric when grading this week's lab.\n\n",
					"textcolor" : [ 0.0, 0.0, 0.501961, 1.0 ]
				}

			}
, 			{
				"box" : 				{
					"fontface" : 1,
					"fontname" : "Helvetica Neue",
					"fontsize" : 12.0,
					"frgb" : 0.0,
					"id" : "obj-6",
					"linecount" : 3,
					"maxclass" : "comment",
					"numinlets" : 1,
					"numoutlets" : 0,
					"patching_rect" : [ 30.0, 105.0, 448.0, 49.0 ],
					"text" : "This week, we looking at recording & playback of control data (Monday) and scheduling rhythmic events (Wednesday). This week's lab gives you several options (pick one of the three below):",
					"textcolor" : [ 0.0, 0.0, 0.501961, 1.0 ]
				}

			}
, 			{
				"box" : 				{
					"fontface" : 1,
					"fontname" : "Helvetica Neue",
					"fontsize" : 20.0,
					"frgb" : 0.0,
					"id" : "obj-3",
					"maxclass" : "comment",
					"numinlets" : 1,
					"numoutlets" : 0,
					"patching_rect" : [ 30.0, 30.0, 339.0, 30.0 ],
					"text" : "LAB 09 // Timing & Scheduling"
				}

			}
, 			{
				"box" : 				{
					"fontface" : 3,
					"fontname" : "Helvetica Neue",
					"fontsize" : 16.0,
					"frgb" : 0.0,
					"id" : "obj-2",
					"maxclass" : "comment",
					"numinlets" : 1,
					"numoutlets" : 0,
					"patching_rect" : [ 30.0, 55.0, 98.0, 26.0 ],
					"text" : "Music 158A"
				}

			}
 ],
		"lines" : [  ],
		"dependency_cache" : [  ]
	}

}
